# Site settings
title: "A HYUN'S RESUME"
description: "웹 개발자 박아현."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "박아현"
resume_title:                   "ABOUT"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "dkgus66@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "010-2847-5700"

display_header_contact_info:    "true"

resume_header_intro: "<p>
                        Front-end developer</br>
                        3년 2개월 경력</br>
                        1993.08.17</br>
                        dkgus66@gmail.com
                      </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_links:           true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/hyunjss/resume"
  # resume_twitter_url:           ""
  # resume_dribbble_url:          ""
  # resume_facebook_url:          ""
  resume_linkedin_url:          "https://linkedin.com/in/아현-박-180463190"
  resume_instagram_url:         "https://www.instagram.com/__dly__bt/"
  # resume_website_url:           ""
  # resume_medium_url:            ""
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
